<?php

	$YOUR_TOKEN_SALT 	  	= 'YOUR_TOKEN'; //to secure api web services
	$YOUR_DB_HOSTNAME 		= 'YOUR_DATABASE_HOSTNAME';
	$YOUR_DB_USERNAME 		= 'YOUR_DATABASE_USERNAME';
	$YOUR_DB_PASSWORD 		= 'YOUR_DATABASE_PASSWORD';
	$YOUR_DB_NAME 	  		= 'YOUR_DATABASE_NAME';
	$YOUR_SMTP_HOST	  		= 'YOUR_SMTP_HOST';
	$YOUR_SMTP_USERNAME	  	= 'YOUR_SMTP_USERNAME';
	$YOUR_SMTP_PASSWORD	  	= 'YOUR_SMTP_PASSWORD';
	$YOUR_SMTP_PORT	  		= 'YOUR_SMTP_PORT';
	$YOUR_MAIL_SENDER	  	= 'YOUR_MAIL_SENDER';
	$YOUR_MAIL_RECIPIENT	= 'YOUR_MAIL_RECIPIENT';
	$YOUR_USER_HASH			= 'YOUR_USER_HASH'; //to hash user id
	$YOUR_APP_LINK 			= 'YOUR_APP_LINK'; //for progressive web app